[project]
name = "p8-ocr-with-ai"
version = "0.0.0"
description = "OCR Application with AI"
requires-python = ">=3.11"

dependencies = [
    "python-dotenv",
    "django>=5.2",
    "openai",
    "llama-cloud>=2.8",
    "llama-index",
    "pydantic",
    "pydantic[email]",
    "python-docx",
    "docxtpl",
    "pymupdf",
    "pandas",
]

[tool.setuptools]
py-modules = ["config"]